### ISSUE TITLE
Resizing Input Image to Multiples of 14 

### ISSUE THREAD

**Issue by Lililiu116** [charliebudd/transferring-relative-monocular-depth-to-surgical-vision#11]
The model input is required to be multiples of 14. If the input image dimensions aren’t multiples of 14 (for example, 512 x 640), how should I resize the image? I am currently working on the StereoMIS dataset and want to keep the processing method consistent with yours.

Thank you!

**Comment by charliebudd** [comment]
Hi there, thanks for asking

The `load_model` function returns a tuple containing...
- The selected model with the weights provided in the function call
- A `Resize` transform configured depending on the model selected
- A `Normalize` transform, again configured for the selected model

I have it so the sizing and normalization is the same as used to train the base models...
- MiDas: `Resize((384, 384)), Normalize(0.5, 0.5)`
- DepthAnything: `Resize((378, 378)), Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])`

So assuming you're using DepthAnything based models, you'll want the later

**Comment by Lililiu116** [comment]
Thank you for the quick response! 
I’m also curious about how you handle predicted depth values. When I simply invert the model’s output to get the predicted depth, I encounter very small values that lead to extremely large outputs, including infinite values. How do you manage this issue? Do you apply a threshold to clamp the output within a specific range?


![Figure_1](https://github.com/user-attachments/assets/a9552bda-ac04-4e8b-814b-a09c4c7d6ec3)

**Comment by charliebudd** [comment]
These models are relative depth models, or to be more precise given the context of this question, relative disparity models (training depth models is generally handled in disparity space precisely because it avoids this instability). As ***relative*** disparity models, the inference for a single image has arbitrary shift and scale. 

You are free to shift and scale the result to within some range that would give nice depth maps by avoiding the singularity at 0. Perhaps defining the maximum and minimum distances you would like to represent and normalising the disparity map to between the inverse of these values.

Whether you want to do this is perhaps a separate question. If this is for aesthetic/qualitative purposes, then it is fine, however for evaluation it would be inaccurate. These models are evaluated against ground truth depth maps by first taking the inverse of the ground truth to get a disparity map, then fitting a scale and shift to align the prediction and ground truth. Performing this fitting in depth space rather than disparity space would be incorrect, as the assumed relationship between the prediction and ground truth would no longer be linear.

In this way we can evaluate the structure of the prediction without worrying about dataset specific factors which would come into play for absolute depth.

**Comment by Lililiu116** [comment]
I understand now, thank you for your reply!
